#!/usr/bin/env zsh

function generate_sample() {
    printf "$1"
    say -o /tmp/robo_voice.wav --data-format=LEF32@22050 "$2" &> /dev/null
    printf "."
    ffmpeg -i /tmp/robo_voice.wav "resources/$1.mp3" &> /dev/null
    echo "mp3"
}

generate_sample "prefix" "Hi. This is Marco Nicoletti from Denver. I made a website that generated this timestamp. This podcast was recorded at."

generate_sample "hour_1" "one"
generate_sample "hour_2" "two"
generate_sample "hour_3" "three"
generate_sample "hour_4" "four"
generate_sample "hour_5" "five"
generate_sample "hour_6" "six"
generate_sample "hour_7" "seven"
generate_sample "hour_8" "eight"
generate_sample "hour_9" "nine"
generate_sample "hour_10" "ten"
generate_sample "hour_11" "eleven"
generate_sample "hour_12" "twelve"

generate_sample "minute_0" "oh clock"
generate_sample "minute_1" "oh one"
generate_sample "minute_2" "oh two"
generate_sample "minute_3" "oh three"
generate_sample "minute_4" "oh four"
generate_sample "minute_5" "oh five"
generate_sample "minute_6" "oh six"
generate_sample "minute_7" "oh seven"
generate_sample "minute_8" "oh eight"
generate_sample "minute_9" "oh nine"
generate_sample "minute_10" "ten"
generate_sample "minute_11" "eleven"
generate_sample "minute_12" "twelve"
generate_sample "minute_13" "thirteen"
generate_sample "minute_14" "fourteen"
generate_sample "minute_15" "fifteen"
generate_sample "minute_16" "sixteen"
generate_sample "minute_17" "seventeen"
generate_sample "minute_18" "eightteen"
generate_sample "minute_19" "nineteen"
generate_sample "minute_20" "twenty"
generate_sample "minute_21" "twenty one"
generate_sample "minute_22" "twenty two"
generate_sample "minute_23" "twenty three"
generate_sample "minute_24" "twenty four"
generate_sample "minute_25" "twenty five"
generate_sample "minute_26" "twenty six"
generate_sample "minute_27" "twenty seven"
generate_sample "minute_28" "twenty eight"
generate_sample "minute_29" "twenty nine"
generate_sample "minute_30" "thirty"
generate_sample "minute_31" "thirty one"
generate_sample "minute_32" "thirty two"
generate_sample "minute_33" "thirty three"
generate_sample "minute_34" "thirty four"
generate_sample "minute_35" "thirty five"
generate_sample "minute_36" "thirty six"
generate_sample "minute_37" "thirty seven"
generate_sample "minute_38" "thirty eight"
generate_sample "minute_39" "thirty nine"
generate_sample "minute_40" "fourty"
generate_sample "minute_41" "fourty one"
generate_sample "minute_42" "fourty two"
generate_sample "minute_43" "fourty three"
generate_sample "minute_44" "fourty four"
generate_sample "minute_45" "fourty five"
generate_sample "minute_46" "fourty six"
generate_sample "minute_47" "fourty seven"
generate_sample "minute_48" "fourty eight"
generate_sample "minute_49" "fourty nine"
generate_sample "minute_50" "fifty"
generate_sample "minute_51" "fifty one"
generate_sample "minute_52" "fifty two"
generate_sample "minute_53" "fifty three"
generate_sample "minute_54" "fifty four"
generate_sample "minute_55" "fifty five"
generate_sample "minute_56" "fifty six"
generate_sample "minute_57" "fifty seven"
generate_sample "minute_58" "fifty eight"
generate_sample "minute_59" "fifty nine"

generate_sample "am" "a m"
generate_sample "pm" "p m"

generate_sample "on" "on"

generate_sample "day_1" "sunday"
generate_sample "day_2" "monday"
generate_sample "day_3" "tuesday"
generate_sample "day_4" "wednesday"
generate_sample "day_5" "thursday"
generate_sample "day_6" "friday"
generate_sample "day_7" "saturday"

generate_sample "month_1" "january"
generate_sample "month_2" "february"
generate_sample "month_3" "march"
generate_sample "month_4" "april"
generate_sample "month_5" "may"
generate_sample "month_6" "june"
generate_sample "month_7" "july"
generate_sample "month_8" "august"
generate_sample "month_9" "september"
generate_sample "month_10" "october"
generate_sample "month_11" "november"
generate_sample "month_12" "december"

generate_sample "date_1"  "first"
generate_sample "date_2"  "second"
generate_sample "date_3"  "third"
generate_sample "date_4"  "fourth"
generate_sample "date_5"  "fifth"
generate_sample "date_6"  "sixth"
generate_sample "date_7"  "seventh"
generate_sample "date_8"  "eighth"
generate_sample "date_9"  "nineth"
generate_sample "date_10" "tenth"
generate_sample "date_11" "eleventh"
generate_sample "date_12" "twelveth"
generate_sample "date_13" "thirteenth"
generate_sample "date_14" "fourteenth"
generate_sample "date_15" "fifteenth"
generate_sample "date_16" "sixteenth"
generate_sample "date_17" "seventeenth"
generate_sample "date_18" "eighteenth"
generate_sample "date_19" "nineteenth"
generate_sample "date_20" "twentieth"
generate_sample "date_21" "twenty first"
generate_sample "date_22" "twenty second"
generate_sample "date_23" "twenty third"
generate_sample "date_24" "twenty fourth"
generate_sample "date_25" "twenty fifth"
generate_sample "date_26" "twenty sixth"
generate_sample "date_27" "twenty seventh"
generate_sample "date_28" "twenty eighth"
generate_sample "date_29" "twenty nineth"
generate_sample "date_30" "thirtieth"
generate_sample "date_31" "thirty first"

generate_sample "suffix" ". Things may have changed by the time you hear it. Keep up with all of NPR’s political coverage at NPR.org and with the NPR One app, or at your local public radio station. Ok, here’s the show!"